package com.revature.exceptions;

public class UserNotFoundException extends Throwable {
    public UserNotFoundException(String no_user_found) {
    }
}
